const products = [

    {
        name: 'VISION 32" LED TV M03 Ultimate',
        img: 'https://i.ibb.co/2j6zXq3/images-1.jpg',
        price: '19350',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'Xiaomi Mi P1 32" HD Android TV L32M6-6AEU Global Version',
        img: 'https://i.ibb.co/8BZ4XdZ/images-2.jpg',
        price: '18350',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'VISION 65" LED TV 3D 4K H01 Smart',
        img: 'https://i.ibb.co/2j6zXq3/images-1.jpg',
        price: '18350',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'Xiaomi Mi P1 32" L32M6-6AEU Global',
        img: 'https://i.ibb.co/cytzR4p/images-4.jpg',
        price: '18350',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'VISION 65" LED TV 3D 4K H01 Smart',
        img: 'https://i.ibb.co/DRhXg0y/images-5.jpg',
        price: '18350',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'Xiaomi Mi P1 32" HD Version',
        img: 'https://i.ibb.co/Cmsj7Kp/images-6.jpg',
        price: '18350',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'VISION 65" LED TV H-02 SMART',
        img: 'https://i.ibb.co/bHP0jSr/images-7.jpg',
        price: '18350',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'Xiaomi Mi P1 32" HD Global Version',
        img: 'https://i.ibb.co/0ymPWsw/images-8.jpg',
        price: '18350',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'VISION 65" LED TV H-02 SMART',
        img: 'https://i.ibb.co/z6CWPyp/images-9.jpg',
        price: '18350',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'Xiaomi Mi P1 32" HD  Global Version',
        img: 'https://i.ibb.co/02rgBNy/images-10.jpg',
        price: '18350',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'VISION 24" LED TV S1 Neo Version',
        img: 'https://i.ibb.co/5FSSRm9/images-11.jpg',
        price: '18350',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'Xiaomi Mi P1 32" HD Android TV L32M6-6AEU Global Version',
        img: 'https://i.ibb.co/KmGbfq8/images-12.jpg',
        price: '18350',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'VISION 24" LED TV S1 Neo Version',
        img: 'https://i.ibb.co/vPRp9v4/images-13.jpg',
        price: '18350',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'Xiaomi Mi P1 32" HD Android TV',
        img: 'https://i.ibb.co/wdNX35y/images.jpg',
        price: '18350',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    }

]















