const Tvproducts = [

    {
        name: 'VISION 32" LED TV M03 Ultimate',
        img: 'https://i.ibb.co/2j6zXq3/images-1.jpg',
        price: '19350',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'Xiaomi Mi P1 32" HD Android TV L32M6-6AEU Global Version',
        img: 'https://i.ibb.co/8BZ4XdZ/images-2.jpg',
        price: '18350',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'VISION 65" LED TV 3D 4K H01 Smart',
        img: 'https://i.ibb.co/2j6zXq3/images-1.jpg',
        price: '18350',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'Xiaomi Mi P1 32" L32M6-6AEU Global',
        img: 'https://i.ibb.co/cytzR4p/images-4.jpg',
        price: '18350',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'VISION 65" LED TV 3D 4K H01 Smart',
        img: 'https://i.ibb.co/DRhXg0y/images-5.jpg',
        price: '18350',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'Xiaomi Mi P1 32" HD Version',
        img: 'https://i.ibb.co/Cmsj7Kp/images-6.jpg',
        price: '18350',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'VISION 65" LED TV H-02 SMART',
        img: 'https://i.ibb.co/bHP0jSr/images-7.jpg',
        price: '18350',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'Xiaomi Mi P1 32" HD Global Version',
        img: 'https://i.ibb.co/0ymPWsw/images-8.jpg',
        price: '18350',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'VISION 65" LED TV H-02 SMART',
        img: 'https://i.ibb.co/z6CWPyp/images-9.jpg',
        price: '18350',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'Xiaomi Mi P1 32" HD  Global Version',
        img: 'https://i.ibb.co/02rgBNy/images-10.jpg',
        price: '18350',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'VISION 24" LED TV S1 Neo Version',
        img: 'https://i.ibb.co/5FSSRm9/images-11.jpg',
        price: '18350',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'Xiaomi Mi P1 32" HD Android TV L32M6-6AEU Global Version',
        img: 'https://i.ibb.co/KmGbfq8/images-12.jpg',
        price: '18350',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'VISION 24" LED TV S1 Neo Version',
        img: 'https://i.ibb.co/vPRp9v4/images-13.jpg',
        price: '18350',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'Xiaomi Mi P1 32" HD Android TV',
        img: 'https://i.ibb.co/wdNX35y/images.jpg',
        price: '18350',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    }

]

const homePagePd = [
    {
        name: 'Headphone Black',
        img: 'https://i.ibb.co/Vg9RLyp/p-1.png',
        price: '1250',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'Smartphone Apple',
        img: 'https://i.ibb.co/x3nJZTW/p-2.png',
        price: '1250',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'Camera Recording Support',
        img: 'https://i.ibb.co/YR4LX2M/n-4.png',
        price: '250',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'Canon Digital Camera W/ 42 ',
        img: 'https://i.ibb.co/3s9Wpgg/n-5.png',
        price: '290',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'Laptop & Computer',
        img: 'https://i.ibb.co/CtHQKTh/p-1.png',
        price: '2050',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'Smartphone Samsung S10',
        img: 'https://i.ibb.co/gFqBGmT/p-2.png',
        price: '1250',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'Endeavor Dryrip Backpack Zoom',
        img: 'https://i.ibb.co/tKHFMHP/p-3.png',
        price: '1250',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'Smartwatch Backpack Zoom',
        img: 'https://i.ibb.co/2WjCW5R/p-3.png',
        price: '1250',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
    {
        name: 'Headphone Black',
        img: 'https://i.ibb.co/zxq8BJY/n-3.png',
        price: '350',
        des1: 'Glossy outlook with User Friendly and Graphically Improved UI',
        des2: '8 ohms 10 Watt*2 speaker',
        des4: 'MVA Panel technology',
        des5: 'Contrast ratio: 3000:1',
        des6: 'Brightness-175 cd/m2',
        des7: 'Resolution: 1366 x 768',
        des8: '1xUSB & 2xHDMI supported',
        Brands: 'VISION',
        Availability: '150 In Stock',
    },
]



























